### ISSUE TITLE
The position of augmentation dataset

### ISSUE THREAD

**Issue by fsted** [Xavier-Pan/WSGCN#3]
Hello, may I ask which directory should the VOC12 augmentation dataset be placed in after downloading, and whether it needs to be converted from .mat format to .jpg/png format
thank you😄

**Comment by Xavier-Pan** [comment]
Hi,

You can place Segmentation ClassAug in VOC12/VOC2012 as shown in the recommended directory structure in README.md
and you don't need to transfer the .mat to the image file as it is already in .png format.
