### ISSUE TITLE
load affinity_feature and affinity_matrix

### ISSUE THREAD

**Issue by puppystellar** [Xavier-Pan/WSGCN#4]
Thanks for your excellent in WSSS. I have some problem with the affinity part. how could we calculate and save the affinity_matrix and affinity_feature properly. Thank you very much!

**Comment by lzc-David** [comment]
Hello，I have same problem that how we calculate and save the affinity_matrix and affinity_feature. Thank you!!

**Comment by Xavier-Pan** [comment]
Hi,

To obtain the affinity_matrix from IRN, you can locate the relevant code on line 162 of the IRN/misc/indexing.py file. This part of the code is responsible for calculating the affinity matrix.

Similarly, for acquiring the affinity_feature from IRN, refer to the code between lines 131 and 133 within the IRN/net/resnet50_irn.py file.
